<a href="https://colab.research.google.com/github/Foluwa/ml-zoomcamp-2024/blob/main/03-classification/homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 3: Machine Learning for Classification for Machine Learning Zoomcamp 2024

In [1]:
!wget https://archive.ics.uci.edu/static/public/222/bank+marketing.zip

--2024-10-16 17:41:15--  https://archive.ics.uci.edu/static/public/222/bank+marketing.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘bank+marketing.zip’

bank+marketing.zip      [ <=>                ] 999.85K  6.00MB/s    in 0.2s

2024-10-16 17:41:16 (6.00 MB/s) - ‘bank+marketing.zip’ saved [1023843]

In [2]:
!unzip bank+marketing.zip

Archive:  bank+marketing.zip
 extracting: bank.zip
 extracting: bank-additional.zip

In [3]:
!unzip bank-additional.zip
!unzip bank.zip

Archive:  bank-additional.zip
   creating: bank-additional/
  inflating: bank-additional/.DS_Store
   creating: __MACOSX/
   creating: __MACOSX/bank-additional/
  inflating: __MACOSX/bank-additional/._.DS_Store
  inflating: bank-additional/.Rhistory
  inflating: bank-additional/bank-additional-full.csv
  inflating: bank-additional/bank-additional-names.txt
  inflating: bank-additional/bank-additional.csv
  inflating: __MACOSX/._bank-additional
Archive:  bank.zip
  inflating: bank-full.csv
  inflating: bank-names.txt
  inflating: bank.csv

In [ ]:
# bank-full.csv

In [4]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('bank-full.csv', sep=';')

In [8]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [9]:
columns = [
    "age",
    "job",
    "marital",
    "education",
    "balance",
    "housing",
    "contact",
    "day",
    "month",
    "duration",
    "campaign",
    "pdays",
    "previous",
    "poutcome",
    "y"
]

In [10]:
df = df[columns]

In [11]:
df.head()

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,29,yes,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,2,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,1506,yes,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,1,no,unknown,5,may,198,1,-1,0,unknown,no

In [12]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 age          0
job          0
marital      0
education    0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

## Question 1
What is the most frequent observation (mode) for the column education?

In [14]:
# Question 1: Find the mode for the 'education' column
education_mode = df['education'].mode()[0]
print("\nThe most frequent observation (mode) for the 'education' column is:", education_mode)

The most frequent observation (mode) for the 'education' column is: secondary

## Question 2

In [13]:
from sklearn.model_selection import train_test_split

# Select numerical features for correlation matrix
numerical_columns = ["age", "balance", "day", "duration", "campaign", "pdays", "previous"]
correlation_matrix = df[numerical_columns].corr()

# Display the correlation matrix
print("Correlation matrix:\n", correlation_matrix)

# Find the two features with the highest correlation
correlation_pairs = correlation_matrix.unstack()
correlation_pairs = correlation_pairs[correlation_pairs != 1].abs().sort_values(ascending=False)
highest_correlation = correlation_pairs.idxmax()
print(f"\nThe two features with the highest correlation are: {highest_correlation[0]} and {highest_correlation[1]}")

# Encode the target variable 'y'
df['y'] = df['y'].map({'yes': 1, 'no': 0})

# Split the data into train, validation, and test sets
X = df.drop(columns=['y'])
y = df['y']

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Output the sizes of each set
print("\nTraining set size:", X_train.shape[0])
print("Validation set size:", X_val.shape[0])
print("Test set size:", X_test.shape[0])

Correlation matrix:
                age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

The two features with the highest correlation are: previous and pdays

Training set size: 27126
Validation set size: 9042
Test set size: 9043

## Question 3

In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import mutual_info_classif

# Define the categorical features to calculate mutual information with y
categorical_features = ["contact", "education", "housing", "poutcome"]
mi_scores = {}

# Calculate mutual information score for each categorical feature
for feature in categorical_features:
    # Encode categorical feature into numerical format
    le = LabelEncoder()
    X_train_encoded = le.fit_transform(X_train[feature])

    # Calculate mutual information between y and the encoded feature
    mi_score = mutual_info_classif(X_train_encoded.reshape(-1, 1), y_train, discrete_features=True)
    mi_scores[feature] = round(mi_score[0], 2)

# Print the mutual information scores for each feature
print("Mutual Information Scores:")
for feature, score in mi_scores.items():
    print(f"{feature}: {score}")

# Find the feature with the highest mutual information score
max_mi_feature = max(mi_scores, key=mi_scores.get)
print(f"\nThe variable with the highest mutual information score is: {max_mi_feature} with a score of {mi_scores[max_mi_feature]}")

Mutual Information Scores:
contact: 0.01
education: 0.0
housing: 0.01
poutcome: 0.03

The variable with the highest mutual information score is: poutcome with a score of 0.03

## Question 4

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# One-hot encode categorical variables
categorical_features = ["job", "marital", "education", "housing", "contact", "month", "poutcome"]
X_train_encoded = pd.get_dummies(X_train, columns=categorical_features, drop_first=True)
X_val_encoded = pd.get_dummies(X_val, columns=categorical_features, drop_first=True)

# Align columns of validation set to match training set columns (in case of missing categories)
X_val_encoded = X_val_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

# Initialize and train the logistic regression model
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train_encoded, y_train)

# Predict on the validation set
y_val_pred = model.predict(X_val_encoded)

# Calculate accuracy
accuracy = accuracy_score(y_val, y_val_pred)
rounded_accuracy = round(accuracy, 2)

print(f"The accuracy on the validation dataset is: {rounded_accuracy}")

The accuracy on the validation dataset is: 0.9

## Question 5

In [17]:
import numpy as np

# Define a function to train the model and calculate accuracy
def train_and_evaluate(features):
    # One-hot encode categorical features and align columns between train and validation sets
    X_train_encoded = pd.get_dummies(X_train[features], drop_first=True)
    X_val_encoded = pd.get_dummies(X_val[features], drop_first=True)
    X_val_encoded = X_val_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

    # Train logistic regression model
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train_encoded, y_train)

    # Predict on validation set and calculate accuracy
    y_val_pred = model.predict(X_val_encoded)
    accuracy = accuracy_score(y_val, y_val_pred)
    return accuracy

# Original model accuracy with all features
all_features = X_train.columns
original_accuracy = train_and_evaluate(all_features)
print(f"Original Accuracy with all features: {round(original_accuracy, 2)}")

# Calculate accuracy difference for each feature
feature_differences = {}
for feature in all_features:
    # Exclude one feature and calculate accuracy
    reduced_features = [f for f in all_features if f != feature]
    reduced_accuracy = train_and_evaluate(reduced_features)

    # Calculate the difference from the original accuracy
    difference = round(original_accuracy - reduced_accuracy, 2)
    feature_differences[feature] = difference
    print(f"Excluding {feature}: Accuracy Difference = {difference}")

# Identify the feature with the smallest difference
least_impact_feature = min(feature_differences, key=feature_differences.get)
print(f"\nThe feature with the smallest impact on accuracy is: {least_impact_feature}")

Original Accuracy with all features: 0.9
Excluding age: Accuracy Difference = -0.0
Excluding job: Accuracy Difference = 0.0
Excluding marital: Accuracy Difference = -0.0
Excluding education: Accuracy Difference = -0.0
Excluding balance: Accuracy Difference = -0.0
Excluding housing: Accuracy Difference = -0.0
Excluding contact: Accuracy Difference = 0.0
Excluding day: Accuracy Difference = -0.0
Excluding month: Accuracy Difference = -0.0
Excluding duration: Accuracy Difference = 0.01
Excluding campaign: Accuracy Difference = -0.0
Excluding pdays: Accuracy Difference = -0.0
Excluding previous: Accuracy Difference = -0.0
Excluding poutcome: Accuracy Difference = 0.01

The feature with the smallest impact on accuracy is: age

# Question 6

In [18]:
# Define the values of C to try
C_values = [0.01, 0.1, 1, 10, 100]
accuracies = {}

# One-hot encode categorical variables for the training and validation sets
X_train_encoded = pd.get_dummies(X_train, drop_first=True)
X_val_encoded = pd.get_dummies(X_val, drop_first=True)
X_val_encoded = X_val_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

# Train logistic regression models for each C value and calculate accuracy on the validation set
for C in C_values:
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train_encoded, y_train)

    # Predict on the validation set
    y_val_pred = model.predict(X_val_encoded)

    # Calculate and round accuracy to 3 decimal places
    accuracy = round(accuracy_score(y_val, y_val_pred), 3)
    accuracies[C] = accuracy
    print(f"C = {C}: Validation Accuracy = {accuracy}")

# Find the best C value
best_C = max(accuracies, key=accuracies.get)
print(f"\nThe best value of C is: {best_C} with an accuracy of {accuracies[best_C]}")

C = 0.01: Validation Accuracy = 0.898
C = 0.1: Validation Accuracy = 0.901
C = 1: Validation Accuracy = 0.9
C = 10: Validation Accuracy = 0.901
C = 100: Validation Accuracy = 0.9

The best value of C is: 0.1 with an accuracy of 0.901